### ISSUE TITLE
Use for own school

### ISSUE THREAD

**Issue by FreshImmuc** [StuBITtv/DBG-Schedule-Sync#2]
Hey,
Can I somehow use this for my school's dsb or is this app **ONLY** for your use?

The Idea is great and i really miss this feature on my school.
I would have all the capabilities to host / set this up buf my question is if you would allow it and if I have to modify much code to actually get it to work with another dsb.

**Comment by hfxbse** [comment]
Of course, you are allowed to adapt it to your needs, else it wouldn't be open source, and I definitely wouldn't have bordered adding a license.

It's hard to tell how much you need to change without knowing how your school organizes its plans and classes. Mine uploads the plans as an HTML table to DSB, but with such inconsistent data entries, sometimes even humans struggle to understand it. Therefore, lots of effort went into parsing and filtering, which may or may not be required in your case. Adapting the web app and calendar stuff should be more straightforward. Though, you might run into breaking changes when updating dependencies, as I did not change much since I'm not attending that school anymore.

I did add some information to the README about which configurations are needed to deploy it. I hope this helps a little :)

**Comment by Rakete2510** [comment]
Danke ja hat etwas geholfen kann man das auch ohne Azure / google cloud machen? und kannst du etwas genauer schreiben wie man die .env ausfüllen muss.

muss die DSB Config schon in die .env rein?

**Comment by hfxbse** [comment]
Ohne ein Google Cloud Projekt wird es spätestens für den Zugriff auf die Google Kalender nicht möglich sein. 

Da die App hauptsächlich auf Firebase als Authentifizierungsprovider und Datenbank aufsetzt, ist dieses nur sehr schwer und mit viel Arbeit zu ändern. Die Free-Tier von Firebase sollte alles abdecken, bis auf die Backend-Funktionen. Diese können prinzipiell auf jeden beliebigen Server lauf, verlieren dann aber die Möglichkeit, direkt auf Ereignisse in der Cloud zu reagieren. Diese Ereignisse werden dazu genutzt, um den Kalender direkt zu aktualisieren, nachdem der Benutzer seine Einstellungen geändert hat. Es sollte möglich sein, diese Funktionalität zu reproduzieren, solange der Server aus dem Internet erreichbar ist. 

Es sollte absolut vermieden werden, die DSB Konfiguration in die `.env`-Datei für das Frontend zu tun, da alles, was dort drin steht, in die Webseite leaken kann, wenn man nicht aufpasst. **Die DSB Konfiguration darf nur auf dem Server zugänglich sein.** 
 
Die meisten Werte der `.env` für das Frontend erhält man, nachdem man eine Web-App im Firebase Projekt registriert hat. Man erhält eine Konfiguration, welche man sich beliebig oft anzeigen lassen kann. Diese kann ohne Probleme ins Frontend gelangen, da sie nicht sicherheitsrelevant ist. Auf der [Registrierungsseite](https://firebase.google.com/docs/web/setup#register-app) sind es dann die einzelnen Werte der `firebaseConfig`-Variable.

![App Registrierungsseite](https://i.imgur.com/gLDcc4h.png)

Die Google OAuth Client ID erhält man, nach der [Registrierung der Client in dem Google Cloud Projekt](https://support.google.com/cloud/answer/6158849?hl=en). Diese wird für den Login und dem Zugriff auf die Kalender durch den Server benötigt.

Die Google Verifikation ID erhält man, sobald man die Webseite in der [Google Search Console](https://search.google.com/search-console) zum Indexen registriert, also dass die Website in der Google Suche auftauchen kann. Dies ist optional.

Die URL für das Preview-Bild kann frei gewählt werden, muss aber eine absolute URL sein, also die gleiche Form wie `https://dbg-schedule-sync.web.app/img/icons/android-chrome-512x512.png` besitzen.

Die `.env`-Datei für das Frontend sollte dann etwa so aussehen:
```
VUE_APP_API_KEY=
VUE_APP_DOMAIN=
VUE_APP_ALT_DOMAIN=
VUE_APP_DATABASE_URL=
VUE_APP_PROJECT_ID=
VUE_APP_STORAGE_BUCKET=
VUE_APP_MESSAGING_SENDER_ID=
VUE_APP_APP_ID=
VUE_APP_MEASUREMENT_ID=
VUE_APP_GOOGLE_OAUTH_CLIENT_ID=

GOOGLE_VERIFICATION_ID_ONE=
GOOGLE_VERIFICATION_ID_TWO=
PREVIEW_IMAGE=
```
